# Generated by Django 4.2.30 on 2026-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_author',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
