# Generated by Django 6.0.5 on 2026-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='book_author',
            field=models.CharField(max_length=200),
        ),
    ]
