# Generated by Django 6.0.5 on 2026-06-01 07:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
