# Generated by Django 6.0.5 on 2026-06-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
