# Generated by Django 6.0.5 on 2026-06-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_comment_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
